"""restore created_at field

Revision ID: 35a7815a5b08
Revises: f0a23c2bdb67
Create Date: 2025-04-13 19:49:21.629284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35a7815a5b08'
down_revision = '954c820d7e2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_stats', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game_stats', 'created_at')
    # ### end Alembic commands ###
