"""Add game_duration column

Revision ID: 5cf017466c3a
Revises: d6a2f378877b
Create Date: 2025-04-09 23:00:20.182258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cf017466c3a'
down_revision = 'd6a2f378877b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
