"""add game_duration

Revision ID: 9ec573118ee3
Revises: b01705179e48
Create Date: 2025-04-16 18:31:10.558313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ec573118ee3'
down_revision = 'b01705179e48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
