"""

Revision ID: de1b724f6c0e
Revises: 9ec573118ee3
Create Date: 2025-04-24 18:58:50.409264

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'de1b724f6c0e'
down_revision = '9ec573118ee3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_stats', sa.Column('user_uid', sa.String(), nullable=True))
    op.alter_column('game_stats', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_game_stats_user_uid'), 'game_stats', ['user_uid'], unique=False)
    op.create_foreign_key(None, 'game_stats', 'users', ['user_uid'], ['uid'])
    op.drop_column('game_stats', 'parse_status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_stats', sa.Column('parse_status', sa.VARCHAR(length=50), server_default=sa.text("'success'::character varying"), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'game_stats', type_='foreignkey')
    op.drop_index(op.f('ix_game_stats_user_uid'), table_name='game_stats')
    op.alter_column('game_stats', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('game_stats', 'user_uid')
    # ### end Alembic commands ###
