"""describe the change

Revision ID: f0a23c2bdb67
Revises: 5cf017466c3a
Create Date: 2025-04-13 19:47:06.688644

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f0a23c2bdb67'
down_revision = '5cf017466c3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_stats', sa.Column('disconnect_detected', sa.Boolean(), nullable=True))
    op.add_column('game_stats', sa.Column('parse_source', sa.String(length=20), nullable=True))
    op.add_column('game_stats', sa.Column('parse_reason', sa.String(length=50), nullable=True))
    op.add_column('game_stats', sa.Column('original_filename', sa.String(length=255), nullable=True))
    op.drop_column('game_stats', 'created_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_stats', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_column('game_stats', 'original_filename')
    op.drop_column('game_stats', 'parse_reason')
    op.drop_column('game_stats', 'parse_source')
    op.drop_column('game_stats', 'disconnect_detected')
    # ### end Alembic commands ###
